version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=smart_scales
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
  wordpress:
    depends_on:
      - "postgres"
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=postgres
      - WORDPRESS_DB_PASSWORD=postgres
      - WORDPRESS_DB_NAME=smart_scales
    volumes:
      - wordpress:/var/www/html
volumes:
  db:
    driver: local
  wordpress:
