"""Added new parameter and email

Revision ID: 2422994a57cd
Revises: 9cda678329af
Create Date: 2023-10-26 10:37:52.397377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2422994a57cd'
down_revision: Union[str, None] = '9cda678329af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('point')
    )
    op.add_column('parameters', sa.Column('temperature', sa.Integer(), nullable=True))
    op.add_column('parameters', sa.Column('pressure', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('point_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'status', ['point_id'], ['point'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'point_id')
    op.drop_column('users', 'email')
    op.drop_column('parameters', 'pressure')
    op.drop_column('parameters', 'temperature')
    op.drop_table('status')
    # ### end Alembic commands ###
