"""Change pressure

Revision ID: 3561b238bd65
Revises: 2422994a57cd
Create Date: 2023-10-26 10:44:47.044635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3561b238bd65'
down_revision: Union[str, None] = '2422994a57cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('systolic_pressure', sa.Integer(), nullable=True))
    op.add_column('parameters', sa.Column('diastolic_pressure', sa.Integer(), nullable=True))
    op.drop_column('parameters', 'pressure')
    op.add_column('standards', sa.Column('pulse', sa.Integer(), nullable=True))
    op.add_column('standards', sa.Column('temperature', sa.Integer(), nullable=True))
    op.add_column('standards', sa.Column('systolic_pressure', sa.Integer(), nullable=True))
    op.add_column('standards', sa.Column('diastolic_pressure', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standards', 'diastolic_pressure')
    op.drop_column('standards', 'systolic_pressure')
    op.drop_column('standards', 'temperature')
    op.drop_column('standards', 'pulse')
    op.add_column('parameters', sa.Column('pressure', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('parameters', 'diastolic_pressure')
    op.drop_column('parameters', 'systolic_pressure')
    # ### end Alembic commands ###
