"""Add back populates to all tables

Revision ID: 66b31c7668ea
Revises: 7759fdbfdc65
Create Date: 2023-11-01 21:37:23.947575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b31c7668ea'
down_revision: Union[str, None] = '7759fdbfdc65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
