"""add null fk

Revision ID: 9cda678329af
Revises: 3036d9dd0d45
Create Date: 2023-09-28 10:13:33.095155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cda678329af'
down_revision: Union[str, None] = '3036d9dd0d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'standards_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'parameters_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'parameters_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'standards_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
